# Generated by Django 6.0.5 on 2026-05-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('engineer_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('installation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('bounding_box', models.JSONField()),
                ('detected_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_engine.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('failure_probability', models.FloatField()),
                ('predicted_failure_date', models.DateField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_engine.tower')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_engine.tower'),
        ),
    ]
